version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: footballdb
    ports:
      - "8100:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
