API:
  key: 2
  version: v1
  format: json
  url_protocol: https
  base_url: www.thesportsdb.com/api
  url:
    list:
      leagues: all_leagues.php
      countries: all_countries.php
      leagues_in_country: search_all_leagues.php
      seasons_in_league: search_all_seasons.php
      teams_in_league: search_all_teams.php
      teams_details_in_league_by_id: lookup_all_teams.php
      players_by_team_id: lookup_all_players.php
    parameters:
      league_param: l
      country_param: c
      sport_param: s
SPORT_WHITELIST: [ 'soccer' ]
LEAGUES_BLACKLIST: [ '_No League' ]
SEASONS_WHITELIST: [ '2021-2022' ]




